### PR TITLE
Modify to use aliases in all actions

### PR DESCRIPTION
**Pull request by Root-kjh**
Alias are difficult to roll back in case of errors if they are performed only in certain actions, so we modified them to use aliases in all actions.
thanks :)

### CODE REVIEW

**Comment by oehrlein** [comment]
@Root-kjh Sorry for the delay in getting back to you - I don't think I ever got a notification that you submitted a PR on this! With that said, I will do my best to look at this in the next week or two, as I'm quite busy at the moment.

**Comment by oehrlein** [comment]
@Root-kjh Hey, just wanted to follow up on this again. I still haven't had a chance to look into this as I've been even busier than when I was in April. Hopefully I'll have time within the next month or so. I appreciate your patience!

**Comment by Root-kjh** [comment]
I understand your situation, and I hope your work goes well. 🙏

**Comment by oehrlein** [comment]
@Root-kjh Thank you!

**Comment by oehrlein** [comment]
@Root-kjh Just wanted to follow up on this - I still haven't had a chance to take a look at this, and probably won't be able to any time soon.

However, my original changes were recently merged into the master branch of django-es/django-elasticsearch-dsl. With that being said, I think it'd be best for you to make a pull request there, as that will be a quicker and more direct way to get these changes merged. Please let me know if that works for you so I can close this pull request.

**Comment by humanscape-june** [comment]
I understand your situation.
So, I will pull it out from the master branch and make a new pr and register it.

**Comment by oehrlein** [comment]
@humanscape-june Thank you so much for understanding!

**Pull request closed without merging**
